name: swipable_stack
description: A widget for stacking cards, which users can swipe horizontally and vertically with beautiful animations like Tinder.
version: 3.0.0
homepage: https://github.com/HeavenOSK/flutter_swipable_stack
environment:
  sdk: ">=3.2.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sprung: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
